### ISSUE TITLE
Basic Authentication and Json Issue with Version 2.0

### ISSUE THREAD

**Issue by simon-wainy** [simple-odata-client/Simple.OData.Client#19]
Hi,

I have used Simple.Odata.Client 2.0 in a PCL within an Xamarin Android project with some success, but I am having problems using it in a basic Console application.
Within the Xamarin PCL, I am able to authenticate my request using Basic Authentication and consume oData using async await accordingly. The Odata that I am consuming is provided by a local test Lightswitch project that I have developed.

I have also added the following code to the BeforeRequest Action to request that the server provides JSON instead of XML, which appears to be working correctly:
MediaTypeWithQualityHeaderValue mthv = new MediaTypeWithQualityHeaderValue("application/json");
            httpRM.Headers.Accept.Add(mthv);

However, I have tried replicating the code in a basic console application so that I can view the requests within Fiddler and run some tests, and I have come across the following issues:
1. When consuming the data Synchronously, I receive the error:
   An unhandled exception of type 'System.Xml.XmlException' occurred in Simple.OData.Client.Net40.dll
   Additional information: Data at the root level is invalid. Line 1, position 1.
   This error occurs when I call FindEntry() on the ODataClient and it appears to not be happy with the Odata being returned in JSON format.
2. If I try to consume the data Asynchronously (exactly as I have done in the PCL), I receive a HTTP/1.1 401 Unauthorized reply instantly.

Can you think of any reason why it would work correctly in a PCL within a Xamarin Android project, but not in a console app, when running exactly the same code?

(I have also tried updating to release 2.0.1)

Thanks,
Simon

**Comment by weitzhandler** [comment]
Do you have to set up JSON manually?
I'm getting the following exception when querying data:

>at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.Throw(String res)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Simple.OData.Client.ODataAdapterFactory.GetMetadataProtocolVersion(String metadataString)
   at Simple.OData.Client.ODataAdapterFactory.CreateModelAdapter(String metadataString, ITypeCache typeCache)
   at Simple.OData.Client.ODataAdapterFactory.CreateAdapterLoader(String metadataString, ITypeCache typeCache)
   at Simple.OData.Client.EdmMetadataCache.GetODataAdapter(ISession session)
   at Simple.OData.Client.Session.Initialize(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.ResolveAdapterAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.FindEntriesAsync(FluentCommand command, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)
   at Simple.OData.Client.FluentClientBase`2.FilterAndTypeColumnsAsync(Task`1 entries, IList`1 selectedColumns, String dynamicPropertiesContainerName)
   at MyProject.Client.ViewModels.ContactsViewModel.LoadAsync()

**Comment by object** [comment]
It looks like your app is unable to retrieve service metadata (it's an XML, not JSON).

**Comment by weitzhandler** [comment]
That was the problem indeed, thanks.

**Comment by emulic** [comment]
@weitzhandler  how did you solve the issue? I'm having the same problem but can't figure out what's going wrong. $metadata route of my service returns valid xml with EDM. The called controller action returns valid odata json structure.
