### ISSUE TITLE
UnresolvableObjectException in Filter on Function results

### ISSUE THREAD

**Issue by watfordgnf** [simple-odata-client/Simple.OData.Client#605]
.NET Framework 4.6.2
Simple.OData.Client 5.6.1
Microsoft.AspNet.OData 7.0.1

I'm receiving an `UnresolvableObjectException` in a location we've not seen before. The code worked on the 4.20+ line without any modifications since. We upgraded to the 5.X line after going to OData 7 on the server side.

Client Code (redacted a bit):
```csharp
            IEnumerable<Scenario> scenarios = await ODataApi.For<Scenario>()
                                      .Function("Default.FunctionName")
                                      .Set(new { onlySuccessful })
                                      .Filter(css => css.StudyID == studyId)
                                      .OrderByDescending(css => css.Started)
                                      .ExecuteAsEnumerableAsync()
                                      .ConfigureAwait(false);
```

Server Code:
```csharp
        [Authorize(Roles = "TheRole")]
        [ODataRoute("Default.FunctionName(onlySuccessful={onlySuccessful})")]
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.All, MaxExpansionDepth = 5)]
        [HttpGet]
        public IQueryable<Scenario> GetStuff([FromODataUri] bool onlySuccessful)
        {
            if (!onlySuccessful)
            {
                return _context.Scenarios
                    .Where(css => !css.MarkedDelete
                        && css.Study.StudyType == StudyType.Something)
                    .AsNoTracking();
            }
            else
            {
                return _context.Scenarios
                    .Where(css => !css.MarkedDelete
                        && css.Study.StudyType == StudyType.Something)
                    .Where(css => css.Instances
                        .Any(csi => csi.Status == CalculatedStatus.Good))
                    .AsNoTracking();
            }
        }
```

Stacktrace:
```
Exception Occurred 2019-04-10T15:56:17.5407516-04:00: 
 Simple.OData.Client.UnresolvableObjectException: Invalid referenced object [StudyID]
   at Simple.OData.Client.ODataExpression.BuildReferencePath(List`1 segmentNames, EntityCollection entityCollection, List`1 elementNames, ExpressionContext context)
   at Simple.OData.Client.ODataExpression.FormatReference(ExpressionContext context)
   at Simple.OData.Client.ODataExpression.Format(ExpressionContext context)
   at Simple.OData.Client.ODataExpression.Format(ExpressionContext context)
   at Simple.OData.Client.FluentCommand.Resolve()
   at Simple.OData.Client.FluentCommand.<GetCommandTextAsync>d__20.MoveNext()
```

Metadata (again, redacted a bit):
```xml
<EntityType Name="Scenario">
<Key>
<PropertyRef Name="ScenarioID"/>
</Key>
<Property Name="ScenarioID" Type="Edm.Int32" Nullable="false"/>
<Property Name="StudyID" Type="Edm.Int32"/>
...
</EntityType>
```

**Comment by vorce** [comment]
@watfordgnf Hello I just bumped into this same issue, did you find a workaround?
