### ISSUE TITLE
System.InvalidOperationException : Sequence contains more than one matching element

### ISSUE THREAD

**Issue by moh-hassan** [simple-odata-client/Simple.OData.Client#610]
I use Simple.OData.Client  Version="5.6.3"
For the service: https://services.odata.org/TripPinRESTierService/People
It's OData service V4

I get this error when executing the following code

             IEnumerable<Person> data = await client.For<Person>()                
                 .FindEntriesAsync();

The Exception details:

>System.InvalidOperationException : Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Simple.OData.Client.V4.Adapter.Metadata.TryGetEntityType(String collectionName, IEdmEntityType& entityType)
   at Simple.OData.Client.V4.Adapter.Metadata.IsTypeWithId(String collectionName)
   at Simple.OData.Client.Adapter.MetadataCache.<IsTypeWithId>b__37_0(String x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Simple.OData.Client.Adapter.MetadataCache.IsTypeWithId(String typeName)
   at Simple.OData.Client.V4.Adapter.ResponseReader.CreateAnnotations(ODataResource odataEntry)
   at Simple.OData.Client.V4.Adapter.ResponseReader.ConvertEntry(ResponseNode entryNode, Object entry)
   at Simple.OData.Client.ResponseReaderBase.EndEntry(Stack`1 nodeStack, ResponseNode& rootNode, Object entry)
   at Simple.OData.Client.V4.Adapter.ResponseReader.ReadResponse(ODataReader odataReader)
   at Simple.OData.Client.V4.Adapter.ResponseReader.GetResponseAsync(IODataResponseMessageAsync responseMessage)
   at Simple.OData.Client.ODataClient.ExecuteRequestWithResultAsync[T](ODataRequest request, CancellationToken cancellationToken, Func`2 createResult, Func`1 createEmptyResult, Func`1 createBatchResult)
   at Simple.OData.Client.ODataClient.FindAnnotatedEntriesAsync(String commandText, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.FindEntriesAsync(FluentCommand command, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)
   at Simple.OData.Client.FluentClientBase`2.FilterAndTypeColumnsAsync(Task`1 entries, IList`1 selectedColumns, String dynamicPropertiesContainerName)
  
The  Request trace:
>GET request: https://services.odata.org/TripPinRESTierService/$metadata
Request completed: OK
GET request: https://services.odata.org/TripPinRESTierService/People
Request completed: OK
  
I noticed in the error  that the method `'FindEntriesAsync' ` call `System.Linq.Enumerable.SingleOrDefault`. 
It is supposed that  `FindEntriesAsync` return collection `IEnumerable<Person>`.

**Comment by moh-hassan** [comment]
When using the serviceUrl: https://services.odata.org/V4/TripPinServiceRW
The exception is disappeared and code is working  fine.

There is a change in the xml schema of both url and also the json format of the returened result.

I couldn't figure why this url: https://services.odata.org/TripPinRESTierService/People raise the exception

Both the odata service url is V4.

**Comment by object** [comment]
Thank you for the issue report. There must be something in TripPinRESTierService schema that causes the failure (this must be a bug in the library).

**Comment by object** [comment]
Fixed. Will be released in 5.7.1.

**Comment by DDeLoachWG** [comment]
@object  Any idea of the timeline for releasing this fix to Nuget as a 5.7.1 package?   Same issue/fix affects talking to MS Azure AD B2C Graph API.  

Interestingly their metadata has other issue as well for collections; the actual AD Graph API URLs don't handle collections as defined in the metadata and the metadata is incomplete for the required collection names, but fortunately it's easy to "fix up" the final URL with the API's requirements during the "before request" phase with only a minor bit of code; though it does require this issue #610 fix to even load the metadata at all.

**Comment by object** [comment]
Sorry for the delay. Released 5.7.1 now.

**Comment by moh-hassan** [comment]
Thanks @object  for the new version.
It's working fine, and the issue is resolved with v 5.7.1
