### ISSUE TITLE
NRE when using client from Visual Basic

### ISSUE THREAD

**Issue by zspitz** [simple-odata-client/Simple.OData.Client#638]
When I use the following C# code:

```csharp
var client = new ODataClient("https://services.odata.org/v4/TripPinServiceRW/");
            
var command = client.For<Person>()
    .Filter(x => x.Trips.Any(y => y.Budget > 3000))
    .Top(2)
    .Select(x => new { x.FirstName, x.LastName });

var commandText = Task.Run(() => command.GetCommandTextAsync()).Result;
// generated relative URL
Console.WriteLine(commandText);
Console.WriteLine();
```

the code runs as expected and ouputs the relative URL. However, if I run the corresponding code in Visual Basic:

```vb
Dim client = New ODataClient("https://services.odata.org/v4/TripPinServiceRW/")

Dim command = client.For(Of Person).
    Filter(Function(x) x.Trips.Any(Function(y) y.Budget > 3000)).
    Top(2).
    Select(Function(x) New With {x.LastName, x.FirstName})

Dim commandText = Task.Run(Function() command.GetCommandTextAsync()).Result
Console.WriteLine(commandText)
Console.WriteLine()
```

I get a NullReferenceException:

> **System.AggregateException**: 'One or more errors occurred. (Object reference not set to an instance of an object.)'
>
> **Inner Exception**
> **NullReferenceException**: Object reference not set to an instance of an object.

The stack trace (for the inner exception) is as follows:

```text
   at Simple.OData.Client.ODataExpression.FormatCallerReference()
   at Simple.OData.Client.ODataExpression.FormatAnyAllFunction(ExpressionContext context)
   at Simple.OData.Client.ODataExpression.FormatFunction(ExpressionContext context)
   at Simple.OData.Client.ODataExpression.Format(ExpressionContext context)
   at Simple.OData.Client.FluentCommand.Resolve()
   at Simple.OData.Client.FluentCommand.GetCommandTextAsync(CancellationToken cancellationToken)
```

I'm using the NuGet package version 5.8.0 of the V4 client.

**Comment by zspitz** [comment]
Apparently, this is because the VB compiler inserts a conversion node whenever the type of the argument doesn't precisely match the parameter. In this case, the first parameter of `Any` is `IEnumerable<Trip>` while the `Trips` property is defined as `ICollection<Trip>`.

The Visual Basic expression tree looks like this:
![image](https://user-images.githubusercontent.com/312166/61474967-65d09a80-a992-11e9-993c-8e29a2147adb.png)

while the C# expression tree looks like this:
![image](https://user-images.githubusercontent.com/312166/61474993-741eb680-a992-11e9-9412-096ba05c43b2.png)

**Comment by object** [comment]
Interesting. Thank you for the investigation. I will think about what can be done here.
