### ISSUE TITLE
FindEntriesAsync unable to parse JSON

### ISSUE THREAD

**Issue by weitzhandler** [simple-odata-client/Simple.OData.Client#646]
Hi,
I'm getting this exception:

>Microsoft.OData.ODataException: 'An unexpected 'StartArray' node was found when reading from the JSON reader. A 'StartObject' node was expected.'

Here's my code:

```c#
var contacts = await _ODataClient
    .For<Contact>()
    .Expand(c => new { c.Phones, c.Emails })
    .Select(c => new ContactDto(c.Id, c.DisplayName, c.Picture, c.Phone, c.Email))
    .FindEntriesAsync();
```
Here's the json response from server:

```json
[
    {
        "Phones": [],
        "Emails": [],
        "Id": 1,
        "DisplayName": "Vagif Abilov",
        "Picture": null
    },
    {
        "Phones": [],
        "Emails": [],
        "Id": 2,
        "DisplayName": "Shimmy Weitzhandler",
        "Picture": null
    }
]
```

StackTrace:

>at Microsoft.OData.Json.JsonReaderExtensions.ValidateNodeType(IJsonReader jsonReader, JsonNodeType expectedNodeType)
at Microsoft.OData.Json.JsonReaderExtensions.ReadNext(IJsonReader jsonReader, JsonNodeType expectedNodeType)
at Microsoft.OData.Json.JsonReaderExtensions.ReadStartObject(IJsonReader jsonReader)
at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStartImplementation(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
at Microsoft.OData.ODataReaderCore.ReadImplementation()
at Microsoft.OData.ODataReaderCore.ReadSynchronously()
at Microsoft.OData.ODataReaderCore.InterceptExceptionT
at Microsoft.OData.ODataReaderCore.Read()
at Simple.OData.Client.V4.Adapter.ResponseReader.ReadResponse(ODataReader odataReader)
at Simple.OData.Client.V4.Adapter.ResponseReader.GetResponseAsync(IODataResponseMessageAsync responseMessage)
at Simple.OData.Client.ODataClient.ExecuteRequestWithResultAsyncT
at Simple.OData.Client.ODataClient.FindAnnotatedEntriesAsync(String commandText, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)
at Simple.OData.Client.ODataClient.FindEntriesAsync(FluentCommand command, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)
at Simple.OData.Client.FluentClientBase2.FilterAndTypeColumnsAsync(Task1 entries, IList`1 selectedColumns, String dynamicPropertiesContainerName)
at MyProject.Client.ViewModels.ContactsViewModel.LoadAsync()

[Here](https://gist.github.com/weitzhandler/a0bc84d715d16dfd2035abcf654d07c2)'s the **metadata** doc.

I tried googling for that exception with OData or ODataException and didn't find anything that could help me, what's wrong?
Thank you!

**Comment by weitzhandler** [comment]
I wish I could debug it and get to the point where its the serializing the JSON, but it comes without a pdb.
I also tried loading symbol from my local clone on the v5 branch, but it couldn't load the symbol ("A matching symbol file was not found in this folder").

**Comment by object** [comment]
The error is thrown from Microsoft.OData.ODataReaderCore, and it's not easy to figure out what is that it's not happy about. You can with some effort debug it though if you get hold of pdb or source files. First thing I would check is to verify if you can make it work with some other client, just to locate the source of the problem: is it the server that is not generating response properly or is it a client lib that doesn't handle it.

**Comment by weitzhandler** [comment]
Thanks for your response, @object!
Is the JSON okay?

**Comment by weitzhandler** [comment]
@object 

> You can with some effort debug it though if you get hold of pdb or source files.

I've spent a fair amount of time trying to plug in debugging symbols in my project, but wasn't able. Please see #653.

> is it the server that is not generating response properly or is it a client lib that doesn't handle it.

The server response JSON looks just fine, so it's a client side error.

**Comment by weitzhandler** [comment]
Apparently, the JSON must include the metadata, and it didn't because it got there through the regular web api route.
