### ISSUE TITLE
Serialization does not working with lower camel case.

### ISSUE THREAD

**Issue by MayorSheFF** [simple-odata-client/Simple.OData.Client#661]
Dear Owner,

I suppose I've run into serialization issue. I have OData endpoint which has been configured to use lower camel case

`odataModelBuilder.EnableLowerCamelCase();`

When I make a request via Postman, all is OK, but when I try to make a request via Simple.OData.Client, I receive the following exception

**Message:**
`The property 'addressID' does not exist on type 'Example.Standard.Database.House'. Make sure to only use property names that are defined by the type or mark the type as open type.`

**StackTrace:**
`at Microsoft.OData.WriterValidationUtils.ValidatePropertyDefined(PropertySerializationInfo propertyInfo, Boolean throwOnUndeclaredProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WritePropertyInfo(ODataPropertyInfo propertyInfo, IEdmStructuredType owningType, Boolean isTopLevel, IDuplicatePropertyNameChecker duplicatePropertyNameChecker, ODataResourceMetadataBuilder metadataBuilder)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, IDuplicatePropertyNameChecker duplicatePropertyNameChecker, ODataResourceMetadataBuilder metadataBuilder)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable1 properties, Boolean isComplexValue, IDuplicatePropertyNameChecker duplicatePropertyNameChecker, ODataResourceMetadataBuilder metadataBuilder)
   at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResource(ODataResource resource)
   at Microsoft.OData.ODataWriterCore.InterceptException(Action action)
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementation(ODataResource resource)
   at Microsoft.OData.TaskUtils.GetTaskForSynchronousOperation(Action synchronousOperation)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.V4.Adapter.RequestWriter.<WriteEntryPropertiesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.V4.Adapter.RequestWriter.<WriteEntryContentAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.RequestWriterBase.<CreateUpdateRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.RequestBuilder.<UpdateRequestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.ODataClient.<UpdateEntryAsync>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.BoundClient1.<UpdateEntryAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Example.Server.Common.ODataClient.<UpdateResourceAsync>d__161.MoveNext()`

Aslo, I added the following settings

`simpleODataClientSettings.NameMatchResolver = ODataNameMatchResolver.AlpahumericCaseInsensitive;`

It did not help me.
House entity contains AddressID property.
OData returns $metadata where all properties are lower camel case.
OData endpoints don't receive the requests.

**Comment by MayorSheFF** [comment]
I've tried to make workaround. I set up

`HttpConfiguration.Formatters.JsonFormatter.SerializerSettings.ContractResolver =
                new CamelCasePropertyNamesContractResolver();`

by means of BeforeRequest action. It works well for FindEntriesAsync request, but it does not work for UpdateEntryAsync. BeforeRequest action is not invoked.

**Comment by axdaws007** [comment]
I have exactly the same problem.  Has anyone come up with a fix or a workaround for the issue?

**Comment by MayorSheFF** [comment]
Ohhh... It will be difficult for me. There are a lot of entities.
