### ISSUE TITLE
Update Many to Many relationship causes Exception

### ISSUE THREAD

**Issue by Allann** [simple-odata-client/Simple.OData.Client#68]
Hi, not sure if this is something I have done wrong in my models as I haven't seen anybody post a similar error.  

To reproduce the exception you can use the following client code:

``` csharp
    ICredentials credentials = CredentialCache.DefaultNetworkCredentials;
    var settings = new ODataClientSettings("http://localhost:53172/", credentials) { OnTrace = (x, y) => Debug.WriteLine("OData: " + x, y) };
    var client = new ODataClient(settings);
    // get existing category
    var category = await client.For<Category>().Filter(c => c.Title == "Test").FindEntryAsync();
    Console.WriteLine(string.Join(", ", category.Id, category.Title));
    // get existing header
    var header = await client.For<Header>().Filter(h => h.Title == "Numeric Tests").Expand(h => h.Categories).FindEntryAsync();
    Console.WriteLine(string.Join(", ", header.Id, header.Title, header.Title));
    // add category to header
    header.Categories.Add(category);
    // update CategoryHeader table
    await client.For<Header>().Key(header.Id).Set(header).UpdateEntryAsync();
```

Client Models (using typed api with matching namespaces):

``` csharp
namespace Jbssa.ElectronicForms.Domain
{
    public sealed class Category 
    {
        public Category()
        {
            Headers = new Collection<Header>();
        }
        public Guid Id { get; set; }
        public string Title { get; set; }
        public ICollection<Header> Headers { get; set; } 
    }

    public class Header
    {
        public Header()
        {
            Categories = new Collection<Category>();
        }
        public Guid Id { get; set; }
        public string Title { get; set; }
        public ICollection<Category> Categories { get; set; }
    }
}
```

Server MetaData (http://localhost:53172/$metadata):

``` xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="Jbssa.ElectronicForms.Domain" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="Category">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Title" Type="Edm.String" Nullable="false" />
        <Property Name="Id" Type="Edm.Guid" Nullable="false" />
        <NavigationProperty Name="Headers" Type="Collection(Jbssa.ElectronicForms.Domain.Header)" />
      </EntityType>
      <EntityType Name="Header">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Title" Type="Edm.String" Nullable="false" />
        <Property Name="Id" Type="Edm.Guid" Nullable="false" />
        <NavigationProperty Name="Categories" Type="Collection(Jbssa.ElectronicForms.Domain.Category)" />
      </EntityType>
    </Schema>
    <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <Action Name="AddStatistics">
        <Parameter Name="ActionKey" Type="Edm.String" Unicode="false" />
        <Parameter Name="PrimaryId" Type="Edm.Guid" Nullable="false" />
      </Action>
      <Function Name="GetMasterEnvironment">
        <ReturnType Type="Jbssa.ElectronicForms.Domain.Master.ServerEnvironment" />
      </Function>
      <EntityContainer Name="Container">
        <EntitySet Name="Categories" EntityType="Jbssa.ElectronicForms.Domain.Category">
          <NavigationPropertyBinding Path="Headers" Target="Headers" />
        </EntitySet>
        <EntitySet Name="Headers" EntityType="Jbssa.ElectronicForms.Domain.Header">
          <NavigationPropertyBinding Path="Categories" Target="Categories" />
        </EntitySet>
        <ActionImport Name="AddStatistics" Action="Default.AddStatistics" />
        <FunctionImport Name="GetMasterEnvironment" Function="Default.GetMasterEnvironment" IncludeInServiceDocument="true" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

Exception: 
    System.ArgumentNullException occurred
      HResult=-2147467261
      Message=Value cannot be null.
    Parameter name: propertyInfo.Target
      Source=Microsoft.OData.Edm
      ParamName=propertyInfo.Target
      StackTrace:
           at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
           at Microsoft.OData.Edm.Library.EdmNavigationProperty.CreateNavigationProperty(IEdmEntityType declaringType, EdmNavigationPropertyInfo propertyInfo)
           at Microsoft.OData.Edm.Library.EdmEntityType.AddUnidirectionalNavigation(EdmNavigationPropertyInfo propertyInfo)
           at Simple.OData.Client.V4.Adapter.EdmDeltaModel..ctor(IEdmModel source, IEdmEntityType entityType, IEnumerable`1 propertyNames)
      InnerException: 

As can be seen in the metadata read by the client, the navigation properties are recognised and when updated on the server (using the server models) the update occurs correctly so EF6.1.1 is doing the right thing with the models.

**Comment by TresaL** [comment]
Hi Allann, how did you make this work?
client.For<Category>().Key(primaryKey).Set(category).UpdateEntryAsync();
 I'm facing the same exception on one to many relationship entity update. Thanks
