### ISSUE TITLE
Loading Metatdata Fails in the presence of a Doctype Definition

### ISSUE THREAD

**Issue by sbrenton** [simple-odata-client/Simple.OData.Client#764]
Hi,
First, thanks all for the work put into this project.  It's been really useful thus far.

Synopsis:
If a dtd tag is present in the metadata doc, the simple odata client fails to load metadata.
There are multiple workaround options but I think this is going to be an ongoing issue.

Here is what I am observing:

1) Before the first service call (or any call to get metadata) ODataAdapterFactory eventually calls GetMetadataProtocolVersion(String metadataString) passing in the string contents of the metadata document.

2) That method uses a flat XmlReader.Create(metadata_doc_string) which will now fail if the inbound response document has any type of DTD.

I think this is a real issue that was likely introduced an update to framework behavior making DTD parsing prohibited by default.
background on the change: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca3075?view=vs-2019

Stack Trace:
Test Outcome:	Failed
Result StackTrace:	
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Simple.OData.Client.ODataAdapterFactory.GetMetadataProtocolVersion(String metadataString)
   at Simple.OData.Client.ODataAdapterFactory.CreateModelAdapter(String metadataString, ITypeCache typeCache)
   at Simple.OData.Client.ODataAdapterFactory.CreateAdapterLoader(String metadataString, ITypeCache typeCache)
   at Simple.OData.Client.EdmMetadataCache.GetODataAdapter(ISession session)
   at Simple.OData.Client.Session.Initialize(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.ResolveAdapterAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.GetMetadataAsync()
   at Rush.Delivery.Test.Experiments.OpenDataWithMongo.CanCreateProfileEntity() in C:\Users\scott\dev\rush\code\app\delivery\test\Experiments\OpenDataWithMongo.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
Result Message:	System.Xml.XmlException : 
For security reasons DTD is prohibited in this XML document. 
To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

workaround options:
- strip dtd server side if possible 
- intercept client responses and strip dtd
- implement ODataAdapterFactory (not designed to support overriding the thing we need to change).
- pass the dtd-less metadata on the client's settings constructor param. 

This issue is tangentially related:
#400 

//sbrenton

**Comment by enantiomer2000** [comment]
also having this issue.
