### ISSUE TITLE
Issues with StringComparison

### ISSUE THREAD

**Issue by RicardoValero95** [simple-odata-client/Simple.OData.Client#775]
I am using Simple OData Client with Blazor Wasm. 

Can someone explain why does this work: 
```csharp
helper.Filter(x => x.Description.Contains(search));
```

But this doesn't:
```csharp
helper.Filter(x => x.Description.Contains(search, StringComparison.InvariantCultureIgnoreCase));
```

I get the following error: 
```
System.NotSupportedException: The function Contains is not supported or called with wrong number of arguments
    at Simple.OData.Client.ODataExpression.FormatFunction(ExpressionContext context)
    at Simple.OData.Client.ODataExpression.Format(ExpressionContext context)
    at Simple.OData.Client.ResolvedCommand.ResolveFilter(FluentCommandDetails details)
    at Simple.OData.Client.ResolvedCommand..ctor(FluentCommand command, ISession session)
    at Simple.OData.Client.FluentCommand.Resolve(ISession session)
    at Simple.OData.Client.RequestBuilder`1.<FindEntriesAsync>d__9[[BlazorApp.Shared.Models.Part, BlazorApp.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
    at BlazorApp.Client.Services.OdataClientService.GetPart(Int32 skip, Int32 top, String search) in C:\...\OdataClientService.cs:line 88
```

**Comment by RicardoValero95** [comment]
Sorry, I'm just dumb.
Here is the correct way.
```chsarp
helper.Filter(x => x.Description.ToLower().Contains(search.ToLower()))
```
Which produces 
```
$filter=contains(tolower(Description),tolower('example'))
```
