### ISSUE TITLE
Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter in SSIS Script Component context

### ISSUE THREAD

**Issue by MichaelSafro** [simple-odata-client/Simple.OData.Client#874]
Hi everyone,

  I am curious if anyone tried using Simple.OData with SSIS Script Component. I was investigating if I could utilize the library in the context of running ETL and encountered the following error when running the package. 
`...Data Flow Task 1, Script Component [23]: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter ---> System.IO.FileLoadException: Could not load file or assembly 'Simple.OData.Client.V4.Adapter' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER)) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.BitConverter.ToString(Byte[] value)
   at Microsoft.SqlServer.IntegrationServices.RuntimeTelemetry.XEventTelemetryService.ResolveXeventReferences(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)...
`

I read a few threads on the topic and tried using ` Simple.OData.Client.V4Adapter.Reference();` to resolve the issue, however, it did not seem to work. The code where I get the runtime is - 
` var someEntityData = _client
           .For("SomeEntityData")
           .FindEntriesAsync().Result;`
The framework that the project targets is 4.7.2 and the library is the latest 5.26 

Similar code run from the console application seems to work fine.

**Comment by tanifort** [comment]
Same here! I just can't make it work, and the error is not helpful

**Comment by DmitryOlenin** [comment]
Same here!
Simple Windows (NOT iOs) service.

"Unable to load OData adapter from assembly Simple.OData.Client.V3.Adapter"

**Comment by skizdigidy** [comment]
I am having the same issue.  I'm attempting to use Simple.OData.V4.Client (6.0.1) and I get this same error.
