### ISSUE TITLE
ReflectionTypeLoadException: Could not load file or assembly 'Microsoft.OData.Core'

### ISSUE THREAD

**Issue by aureole82** [simple-odata-client/Simple.OData.Client#886]
Using NuGet package [Simple.OData.V4.Client 6.0.1](https://www.nuget.org/packages/Simple.OData.V4.Client/6.0.1) I get the following exception on every request:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter
  Source=Simple.OData.Client.Core
  StackTrace:
   at Simple.OData.Client.ODataAdapterFactory.LoadModelAdapter(ITypeCache typeCache, String modelAdapterAssemblyName, String modelAdapterTypeName, Object[] ctorParams)
   at Simple.OData.Client.ODataAdapterFactory.<>c__DisplayClass11_0.<GetModelAdapterLoader>b__1()
   at Simple.OData.Client.ODataAdapterFactory.CreateAdapterLoader(String metadataString, ITypeCache typeCache)
   at Simple.OData.Client.EdmMetadataCache.GetODataAdapter(ISession session)
   at Simple.OData.Client.Session.<Initialize>d__19.MoveNext()
   at Simple.OData.Client.Session.<ResolveAdapterAsync>d__22.MoveNext()
   at Simple.OData.Client.ODataClient.<FindEntryAsync>d__92.MoveNext()
   at Simple.OData.Client.FluentClientBase`2.<FilterAndTypeColumnsAsync>d__98.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Sources\ConsoleApp1\ConsoleApp1\Program.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.OData.Edm, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

```

Solution:
You should add [Microsoft.OData.Core](https://www.nuget.org/packages/Microsoft.OData.Core) as dependency. (At least adding this manually fixes the issue on my machine).

**Comment by giarico** [comment]
I can't understand why this is not already solved after 3 months.
Without this workaround nothing works.

Is this project still alive??

**Comment by stefankaufmann** [comment]
I got so frustrated of this fix, that I created a Pull Request. Would be awesome, if you can provide a new nuget package containing the fix. Thanks.

**Comment by esbenbach** [comment]
@davidnmbond  you are the only recent contributor in the commits history.
Do you have the power/permissions to approve and merge the PR opened by @stefankaufmann ?

**Comment by robertgro** [comment]
Pushing this, because resolving the issue and merging the PR are still in pending state.

**Comment by GerkinDev** [comment]
Had the same problem. I managed to work around it by explicitly specifying the version I want of the transitive dependency.

In csproj:

```xml
    <PackageReference Include="Microsoft.OData.Core" Version="7.10.0" />
    <PackageReference Include="Microsoft.OData.Edm" Version="7.10.0" />
```
